Task #8269: Create UI for Log In Screen
awesome-academy/ios-nd-money_asterisk pull request #7
Opened 2019-03-13 10:54 UTC by tanbtd-1747

### Issue Link :link:
https://edu-redmine.framgia.vn/issues/8269

### Implementation Details :construction:
<img src="https://user-images.githubusercontent.com/47616986/54273699-05cb8100-45b9-11e9-8af5-4df9f97d5152.png" width="300" />

2019-03-13 10:57 UTC, thanhlong12312 commented on Money*/Money*/Scenes/Login/LoginViewController.swift
> +class LoginViewController: UIViewController {
add final

2019-03-13 10:58 UTC, thanhlong12312 commented on Money*/Money*/Scenes/Login/LoginViewController.swift
> +    @IBOutlet var containerEmail: UIView!
add private tương tự ở dưới

2019-03-13 10:59 UTC, thanhlong12312 commented on Money*/Money*/Utils/Theme.swift
> +    struct Color {
cho các màu vào 1 file extension UIColor

2019-03-13 10:59 UTC, thanhlong12312 commented on Money*/Money*/Widgets/GradientView.swift
> +class GradientView: UIView {
add final

2019-03-13 10:59 UTC, thanhlong12312 commented on Money*/Money*/Widgets/RoundedButton.swift
> +class RoundedButton: UIButton {
add final

2019-03-13 13:26 UTC, tgdong2296 commented on Money*/Money*/Utils/Theme.swift
> +        static let ivory = UIColor(red: 255 / 255, green: 255 / 255, blue: 243 / 255, alpha: 1)
```suggestion
        @nonobjc class var ivory: UIColor {
            return UIColor(red: 255 / 255, green: 255 / 255, blue: 243 / 255, alpha: 1)
        }
```
viết trong extention của UIColor, tương tự với những cái bên dưới
khi gọi thì có thể gọi luôn là `.ivory` thay vì `UIColor.ivory`

2019-03-13 13:26 UTC, tgdong2296 commented on Money*/Money*/Widgets/RoundedButton.swift
> +class RoundedButton: UIButton {
cái này nên viết @IBInspectable hoặc 1 hàm round cho extension UIButton sẽ hợp lý hơn

2019-03-13 14:02 UTC, minhduc2511 requested changes

2019-03-13 14:02 UTC, minhduc2511 commented on Money*/Money*/Utils/Theme.swift
> +        static let khaki = UIColor(red: 183 / 255, green: 173 / 255, blue: 153 / 255, alpha: 1)
```suggestion
        static let khaki = UIColor(red: 183 / 255, green: 173 / 255, blue: 153 / 255, alpha: 1)
        
extension UIColor {
    convenience init(r: CGFloat, g: CGFloat, b: CGFloat, a: CGFloat = 1) {
        self.init(red: r/255, green: g/255, blue: b/255, alpha: a)
    }
    static let magicPotion = UIColor(r: 255, g: 67, b: 101)
}
```

2019-03-14 02:17 UTC, thanhlong12312 commented on Money*/Money*/Utils/Theme.swift
> +    struct Param {
Đổi tên thành Constant

2019-03-14 02:17 UTC, tgdong2296 approved these changes

2019-03-14 02:22 UTC, dongsonbk58 approved these changes

2019-03-14 02:38 UTC, minhduc2511 approved these changes

2019-03-14 02:44 UTC, longvt96 approved these changes

2019-03-14 02:45 UTC, nguyenck-1-1519 approved these changes

2019-03-14 06:04 UTC, tienpx3010 approved these changes

2019-03-14 06:05 UTC, tanbtd-1747 commented
ready

2019-03-14 06:06 UTC, merged